name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'vX.Y.Z'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build (ShadowJar)
        run: ./gradlew ShadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ribbon-jar
          path: build/libs/Ribbon-${{ inputs.tag }}.jar
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ribbon-jar

      - name: Get current date
        id: get_date
        run: echo "current_date=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: Ribbon-${{ inputs.tag }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}
          draft: true
          body: |
            ## ${{ inputs.tag }} (${{ env.current_date }})
            
            <!-- Add release notes here -->
